---
name: main

on:
  push:
    branches:
      - main
    

jobs:
  target:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      
      - uses: actions/setup-node@v7
        with:
          node-version: 22
          package-manager-cache: false

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v6
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: install yarn
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm i -g yarn@1.22.22

      - run: yarn install --frozen-lockfile
        if: steps.cache-node-modules.outputs.cache-hit != 'true'

  lint:
    runs-on: ubuntu-latest
    needs:
      - target
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v7
        with:
          node-version: 22
          package-manager-cache: false

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v6
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: lint
        run: npm run affected
        env:
          TARGET: lint
          BASE: main~1
          HEAD: main
        
  test:
    runs-on: ubuntu-latest
    needs:
      - target
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v7
        with:
          node-version: 22
          package-manager-cache: false

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v6
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: test
        run: npm run affected
        env:
          TARGET: test
          BASE: main~1
          HEAD: main
        
  build:
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v7
        with:
          node-version: 22
          package-manager-cache: false

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v6
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: db:generate rule
        run: npm run affected
        env:
          TARGET: db:generate
          BASE: main~1
          HEAD: main

      - name: build
        run: npm run affected
        env:
          TARGET: build
          BASE: main~1
          HEAD: main
      
      - name: Cache dist
        id: cache-dist
        uses: actions/cache@v6
        with:
          path: |
            **/dist
            **/generated
          key: ${{ runner.os }}-dist-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-dist-

  docker:
    runs-on: ubuntu-latest
    needs:
      - build
    env:
      PROJECT_NAME: ${{ vars.PROJECT_NAME }}
      PROJECT: ${{ vars.PROJECT }}
      ENVIRONMENT: ${{ vars.ENVIRONMENT }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v7
        with:
          node-version: 22
          package-manager-cache: false

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v6
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Restore dist
        id: cache-dist
        uses: actions/cache@v6
        with:
          path: |
            **/dist
            **/generated
          key: ${{ runner.os }}-dist-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-dist-

      - name: prune-lockfile
        run: npm run affected
        env:
          TARGET: prune-lockfile
          BASE: main~1
          HEAD: main

      - name: docker
        run: npm run affected
        env:
          TARGET: docker
          BASE: main~1
          HEAD: main

      - name: docker:push
        run: npm run affected
        env:
          TARGET: docker:push
          BASE: main~1
          HEAD: main

## to do is push to ecr and register task definition
